language: ruby
dist: focal
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
    after_success:
      - coveralls
  - rvm: 2.5.8
    env:
      - LABEL=unit_tests
  - rvm: 2.6.6
    env:
      - LABEL=unit_tests
  - rvm: 2.7.2
    env:
      - LABEL=unit_tests
  - rvm: 2.5.8
    env:
      - LABEL=gem_integration_tests
    script:
      - gem install ssh_scan
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.6.6
    env:
      - LABEL=gem_integration_tests
    script:
      - gem install ssh_scan
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.7.2
    env:
      - LABEL=src_integration_tests
    script:
      - bundle install
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.7.2
    env:
      - LABEL=docker_integration_tests
    services:
      - docker
    script:
      - docker build -t mozilla/ssh_scan .
      - docker run -it mozilla/ssh_scan /app/spec/ssh_scan/integration.sh
  - rvm: 2.7.2
    env:
      - LABEL=docker_build_and_push
    services:
      - docker
    script:
      - docker buildx version
      - chmod u+x ./build_and_deploy_to_dockerhub.sh
      - ./build_and_deploy_to_dockerhub.sh
